name: wisata_candi_aldi_yonatan
description: A demo app for Wisata Candi
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
flutter:
  uses-material-design: true

  assets:
    - assets/images/borobudur.jpg
    - assets/images/prambanan.jpg
    - assets/images/mendut.jpg
