name: wisata_candi_aldi_yonatan
description: A demo app for Wisata Candi
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
flutter:
uses-material-design: true

assets:
    - images/borobudur.jpeg
    - images/jago.jpeg
    - images/kalasan.jpeg
    - images/logo_candi.png
    - images/lumbung.jpeg
    - images/mendut.jpeg
    - images/placeholder_image.png
    - images/plaosan.jpeg
    - images/prambanan.jpeg
    - images/sari.jpeg
    - images/sewu.jpeg
    - images/singosari.jpeg
